# -*- coding: utf-8 -*-
"""
/***************************************************************************
 agrae
                                 A QGIS plugin
 Conjunto de herramientas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-03
        copyright            : (C) 2021 by  aGrae Solutions, S.L.
        email                : info@agrae.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load agrae class from file agrae.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .agrae import agrae
    return agrae(iface)
