# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\FRANCISCO\AppData\Roaming\QGIS\QGIS3\profiles\agrae\python\plugins\agrae\ui\agrae_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_agraeDockWidgetBase(object):
    def setupUi(self, agraeDockWidgetBase):
        agraeDockWidgetBase.setObjectName("agraeDockWidgetBase")
        agraeDockWidgetBase.resize(300, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(agraeDockWidgetBase.sizePolicy().hasHeightForWidth())
        agraeDockWidgetBase.setSizePolicy(sizePolicy)
        agraeDockWidgetBase.setMinimumSize(QtCore.QSize(300, 163))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.dockWidgetContents)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 282, 406))
        self.page.setObjectName("page")
        self.geom_check = QtWidgets.QCheckBox(self.page)
        self.geom_check.setGeometry(QtCore.QRect(0, 60, 174, 17))
        self.geom_check.setObjectName("geom_check")
        self.list_btn = QtWidgets.QPushButton(self.page)
        self.list_btn.setGeometry(QtCore.QRect(180, 29, 89, 23))
        self.list_btn.setObjectName("list_btn")
        self.layers_combo = QtWidgets.QComboBox(self.page)
        self.layers_combo.setGeometry(QtCore.QRect(0, 30, 174, 20))
        self.layers_combo.setObjectName("layers_combo")
        self.load_1_btn = QtWidgets.QPushButton(self.page)
        self.load_1_btn.setGeometry(QtCore.QRect(0, 100, 261, 23))
        self.load_1_btn.setObjectName("load_1_btn")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 10, 171, 16))
        self.label.setObjectName("label")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 282, 406))
        self.page_2.setObjectName("page_2")
        self.load_feat_btn = QtWidgets.QPushButton(self.page_2)
        self.load_feat_btn.setGeometry(QtCore.QRect(200, 70, 75, 23))
        self.load_feat_btn.setObjectName("load_feat_btn")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 231, 16))
        self.label_2.setObjectName("label_2")
        self.combo_load_layers = QtWidgets.QComboBox(self.page_2)
        self.combo_load_layers.setGeometry(QtCore.QRect(130, 40, 141, 22))
        self.combo_load_layers.setObjectName("combo_load_layers")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 231, 16))
        self.label_4.setObjectName("label_4")
        self.create_reticule = QtWidgets.QPushButton(self.page_2)
        self.create_reticule.setGeometry(QtCore.QRect(180, 140, 91, 23))
        self.create_reticule.setObjectName("create_reticule")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 161, 31))
        self.label_5.setObjectName("label_5")
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        agraeDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(agraeDockWidgetBase)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(agraeDockWidgetBase)

    def retranslateUi(self, agraeDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        agraeDockWidgetBase.setWindowTitle(_translate("agraeDockWidgetBase", "aGrae GIS"))
        self.geom_check.setText(_translate("agraeDockWidgetBase", "Listar solo tablas con geometria"))
        self.list_btn.setText(_translate("agraeDockWidgetBase", "Listar"))
        self.load_1_btn.setText(_translate("agraeDockWidgetBase", "Anadir Capa al Mapa"))
        self.label.setText(_translate("agraeDockWidgetBase", "Lista de Tablas"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("agraeDockWidgetBase", "Cargar Capas"))
        self.load_feat_btn.setText(_translate("agraeDockWidgetBase", "Cargar"))
        self.label_2.setText(_translate("agraeDockWidgetBase", "1) Añadir Objetos espaciales a la base de datos"))
        self.label_3.setText(_translate("agraeDockWidgetBase", "<html><head/><body><p>Seleccionar tabla a <br> cargar información</p></body></html>"))
        self.label_4.setText(_translate("agraeDockWidgetBase", "2) Crear Reticula Base"))
        self.create_reticule.setText(_translate("agraeDockWidgetBase", "Crear Reticula"))
        self.label_5.setText(_translate("agraeDockWidgetBase", "<html><head/><body><p>Seleccionar el lote o parcela <br> para crear la Reticula</p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("agraeDockWidgetBase", "Funciones Espaciales"))

